animais = ['Gato', 'Cachorro', 'Elefante']
print(animais)
animais.append('Galinha')
print(animais)
animais.insert(0, 'Papagaio')
print(animais)
animais.pop(0)
print(animais)
animais.remove('Gato')
print(animais)
